[package]
name = "vine-macros"
version = "0.1.4-dev.6"
edition = "2021"

license = "Apache-2.0"
description = """
Vine Macros contains macros
"""

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.66", features = ["full"] }
quote = { version = "1.0.36" }
proc-macro2 = { version = "1.0.85" }