[package]
name = "vine-axum-macros"
version = "0.1.4"
edition = "2021"

license = "Apache-2.0"
description = """
vine-axum-macros contains macros for simpler integration with axum framework
"""

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.66", features = ["full"] }
quote = { version = "1.0.36" }
proc-macro2 = { version = "1.0.85" }