[package]
name = "vine"
version = "0.1.4"
edition = "2021"

license = "Apache-2.0"
description = """
Vine is rust framework inspired by Spring Boot
"""

[features]
default = [
    "vine-core",
    "vine-macros",
    "vine-axum",
    "vine-axum-macros"
]

[dependencies]
vine-core = { version = "0.1.4", optional = true }
vine-macros = { version = "0.1.4", optional = true }

vine-axum = { version = "0.1.4", optional = true }
vine-axum-macros = { version = "0.1.4", optional = true }

linkme = "0.3.28"
async-trait = "0.1.82"
config = "0.14.0"
