[package]
name = "vine"
version = "0.1.2"
edition = "2021"

license = "Apache-2.0"
description = """
Vine is rust framework inspired by Spring Boot
"""

[features]
default = [
    "vine-core",
    "vine-macros"
]

[dependencies]
vine-core = { version = "0.1.1", optional = true }
vine-macros = { version = "0.1.2", optional = true }

lazy_static = { version = "1.5.0" }
async-trait = { version = "0.1.81" }
linkme = { version = "0.3.27"}
linkme-impl = { version = "0.3.27" }