[package]
name = "vine"
version = "0.1.4-dev.8"
edition = "2021"

license = "Apache-2.0"
description = """
Vine is rust framework inspired by Spring Boot
"""

[features]
default = [
    "vine-core",
    "vine-macros",
    "vine-axum",
    "vine-axum-macros"
]

[dependencies]
vine-core = { version = "0.1.4-dev.8", optional = true }
vine-macros = { version = "0.1.4-dev.6", optional = true }
vine-axum = { version = "0.1.4-dev.6", optional = true }
vine-axum-macros = { version = "0.1.4-dev.6", optional = true }
