[package]
name = "vine"
version = "0.1.3-dev.1"
edition = "2021"

license = "Apache-2.0"
description = """
Vine is rust framework inspired by Spring Boot
"""

[features]
default = [
    "vine-core",
    "vine-macros"
]

[dependencies]
vine-core = { version = "0.1.3", optional = true }
vine-macros = { version = "0.1.2", optional = true }