[package]
name = "vine-core"
version = "0.1.0"
edition = "2021"

license = "Apache-2.0"
description = """
Vine Core implement core concepts of vine framework.
"""

[dependencies]
log = { version = "0.4.22" }
dashmap = { version = "6.0.1" }
lazy_static = { version = "1.5.0" }
async-trait = { version = "0.1.81" }
linkme = { version = "0.3.27" }